import type { SchemaObject, SchemaOrBoolean } from "@oaverify/internal-core";
import { builtInFormats } from "@oaverify/internal-formats";
import {
  compileSchema,
  jsonSchemaDialect,
  oas30Dialect,
  openapi31Dialect,
  walkSubschemas,
  type Dialect,
} from "@oaverify/internal-schema";

/**
 * Dialect the standalone emitter supports. Values match the CLI's
 * `--dialect` flag so the mapping is trivial.
 *
 * @public
 */
export type StandaloneDialect = "2020-12" | "openapi-3.1" | "openapi-3.0";

const DIALECT_MAP: Record<StandaloneDialect, Dialect> = {
  "2020-12": jsonSchemaDialect,
  "openapi-3.1": openapi31Dialect,
  "openapi-3.0": oas30Dialect,
};

/**
 * Options for {@link emitStandalone}.
 *
 * @internal
 */
export interface EmitStandaloneOptions {
  dialect: StandaloneDialect;
  /**
   * Import-path prefix for runtime deps in the emitted module.
   * Defaults to `"@oaverify/core"` (the published library). Tests
   * use workspace aliases for that same published name, so generated
   * output exercises the real import path.
   */
  importPrefix?: string;
  /**
   * Policy for `format` names outside the built-in set. `"error"`
   * (the default) refuses the schema, naming the formats; `"ignore"`
   * emits a validator that does not assert them, matching the
   * runtime's behavior for an unregistered name. Mirrors
   * `CompileOptions.unknownFormats`. This is policy, not capability:
   * an unknown name has no validator function to serialise either
   * way, so both modes produce the same (correct) module when they
   * produce one.
   */
  unknownFormats?: "ignore" | "error";
}

/**
 * Compile a JSON Schema and emit a standalone ES module source string.
 *
 * The module exports a `validate(data)` function whose behavior
 * matches `compileSchema(schema, { dialect }).validate(data)`, but
 * which requires no `new Function()` at load time. Useful for edge
 * runtimes (Cloudflare Workers, Vercel Edge) and build-time-prepared
 * validator bundles.
 *
 * By default, rejects schemas that use `format: "..."` values outside
 * {@link @oaverify/core/formats!builtInFormats}; `unknownFormats:
 * "ignore"` emits anyway, without asserting them (#660). That is
 * policy. The hard constraint is different and unconditional: a custom
 * format *function* or custom keyword registered at runtime is not
 * serialisable to standalone source, and no option changes that.
 * `int32` and `int64` are built-ins, so they emit rather than being
 * refused.
 *
 * @internal
 */
export function emitStandalone(schema: SchemaOrBoolean, options: EmitStandaloneOptions): string {
  const dialect = DIALECT_MAP[options.dialect];
  const importPrefix = options.importPrefix ?? "@oaverify/core";

  const unknownFormats =
    (options.unknownFormats ?? "error") === "error" ? collectUnknownFormats(schema) : [];
  if (unknownFormats.length > 0) {
    throw new Error(
      `Schema references format${unknownFormats.length > 1 ? "s" : ""} ` +
        `not in the built-in set: ${unknownFormats.map((f) => `"${f}"`).join(", ")}. ` +
        `Standalone compilation asserts only the built-in formats from @oaverify/core/formats; ` +
        `pass --unknown-formats ignore to emit without asserting them.`,
    );
  }

  // Compiled with the same registry the emitted module loads, so a
  // format's declared type is the same on both sides. Codegen reads
  // those types (an `int32` site emits a number guard), and before
  // numeric formats existed this call passed no registry at all.
  const { source } = compileSchema(schema, { dialect, formats: builtInFormats });

  // Assemble the module:
  //   - ESM imports for runtime helpers and the built-in format set.
  //   - Construct `deps` at module scope. Every format validator
  //     registered on `deps.formats` so the compiled validators can
  //     resolve `format: "email"` etc.
  //   - Wrap the compiler's generated source (which is a function
  //     body ending with `return { validate };`) in an IIFE so its
  //     `deps` parameter resolves to our module-scope constant.
  //   - Re-export `validate` at module scope.
  return [
    "// Generated by the oaverify CLI's `compile-schema` command. Do not edit by hand.",
    "// Regenerate by running `oaverify compile-schema <schema>` against the source schema.",
    "",
    `import { createLeafError, createBranchError, createError, normalizeFormat } from "${importPrefix}/core";`,
    `import { createDeps, deepEqual, typeOf, wrapErrors } from "${importPrefix}/schema/internals";`,
    `import { builtInFormats } from "${importPrefix}/formats";`,
    "",
    "// Silence unused-import warnings when the schema doesn't reach a",
    "// given helper. The compiler's output only references the ones it",
    "// needs, so some imports may appear unused at module scope.",
    "void createLeafError; void createBranchError; void createError;",
    "void deepEqual; void typeOf; void wrapErrors;",
    "",
    "const deps = createDeps();",
    "for (const [name, def] of Object.entries(builtInFormats)) deps.formats.set(name, normalizeFormat(def));",
    "",
    "const { validate } = (function (deps) {",
    source,
    "})(deps);",
    "",
    "export { validate };",
    "",
  ].join("\n");
}

/**
 * Formats that the emitted module's `createDeps()` call auto-registers
 * on top of the entries merged in from `builtInFormats`. Mirrors the
 * runtime side of `@oaverify/core/schema`'s `createDeps`; if that list ever
 * grows, this set has to grow too.
 */
const SCHEMA_AUTO_REGISTERED_FORMATS: ReadonlySet<string> = new Set(["regex"]);

/**
 * True when `name` has no validator in the set the emitted module
 * registers (the built-ins plus the schema-auto-registered `regex`), so
 * a guard emitted for it can never fire.
 */
export function isUnknownFormat(name: string): boolean {
  return !(name in builtInFormats) && !SCHEMA_AUTO_REGISTERED_FORMATS.has(name);
}

/**
 * Walk the schema looking for `format: "..."` values referenced on
 * object subschemas; return those not covered by the built-in set or
 * the schema-auto-registered set. Using {@link walkSubschemas} keeps
 * us out of `enum` / `const` / `default` literal values, which might
 * incidentally contain a string under a `format` key without being a
 * format assertion. Does not follow `$ref`; the document-level
 * collector in emit-spec.ts covers the spec case.
 */
export function collectUnknownFormats(schema: SchemaOrBoolean): string[] {
  const found = new Set<string>();
  walkSubschemas(schema, (node) => {
    if (typeof node !== "object" || node === null || Array.isArray(node)) return;
    const format = (node as SchemaObject).format;
    if (typeof format === "string" && isUnknownFormat(format)) {
      found.add(format);
    }
  });
  return [...found].sort();
}
