import type { SchemaObject, SchemaOrBoolean } from "@oav/core";
import { builtInFormats } from "@oav/formats";
import {
  compileSchema,
  jsonSchemaDialect,
  oas30Dialect,
  openapi31Dialect,
  walkSubschemas,
  type Dialect,
} from "@oav/schema";

/**
 * Dialect the standalone emitter supports. Values match the CLI's
 * `--dialect` flag so the mapping is trivial.
 *
 * @public
 */
export type StandaloneDialect = "2020-12" | "openapi-3.1" | "openapi-3.0";

const DIALECT_MAP: Record<StandaloneDialect, Dialect> = {
  "2020-12": jsonSchemaDialect,
  "openapi-3.1": openapi31Dialect,
  "openapi-3.0": oas30Dialect,
};

/**
 * Options for {@link emitStandalone}.
 *
 * @internal
 */
export interface EmitStandaloneOptions {
  dialect: StandaloneDialect;
  /**
   * Import-path prefix for runtime deps in the emitted module.
   * Defaults to `"oav"` (the published name). Tests
   * override to `"@oav"` so the output resolves against the
   * workspace aliases instead of a published tarball.
   */
  importPrefix?: string;
}

/**
 * Compile a JSON Schema and emit a standalone ES module source string.
 *
 * The module exports a `validate(data)` function whose behavior
 * matches `compileSchema(schema, { dialect }).validate(data)`, but
 * which requires no `new Function()` at load time. Useful for edge
 * runtimes (Cloudflare Workers, Vercel Edge) and build-time-prepared
 * validator bundles.
 *
 * Rejects schemas that use `format: "..."` values outside
 * {@link @aahoughton/oav-core/formats!builtInFormats}. Custom formats and
 * custom keywords aren't serialisable and require a more involved
 * emission path; out of scope for the CLI entry.
 *
 * @internal
 */
export function emitStandalone(schema: SchemaOrBoolean, options: EmitStandaloneOptions): string {
  const dialect = DIALECT_MAP[options.dialect];
  const importPrefix = options.importPrefix ?? "@aahoughton/oav-core";

  const unknownFormats = collectUnknownFormats(schema);
  if (unknownFormats.length > 0) {
    throw new Error(
      `Schema references format${unknownFormats.length > 1 ? "s" : ""} ` +
        `not in the built-in set: ${unknownFormats.map((f) => `"${f}"`).join(", ")}. ` +
        `Standalone compilation only supports the built-in formats from @aahoughton/oav-core/formats.`,
    );
  }

  const { source } = compileSchema(schema, { dialect });

  // Assemble the module:
  //   - ESM imports for runtime helpers and the built-in format set.
  //   - Construct `deps` at module scope. Every format validator
  //     registered on `deps.formats` so the compiled validators can
  //     resolve `format: "email"` etc.
  //   - Wrap the compiler's generated source (which is a function
  //     body ending with `return { validate };`) in an IIFE so its
  //     `deps` parameter resolves to our module-scope constant.
  //   - Re-export `validate` at module scope.
  return [
    "// Generated by the oav CLI's `compile` command. Do not edit by hand.",
    "// Regenerate by running `oav compile <schema>` against the source schema.",
    "",
    `import { createLeafError, createBranchError, createError } from "${importPrefix}/core";`,
    `import { createDeps, deepEqual, typeOf, wrapErrors } from "${importPrefix}/schema/internals";`,
    `import { builtInFormats } from "${importPrefix}/formats";`,
    "",
    "// Silence unused-import warnings when the schema doesn't reach a",
    "// given helper. The compiler's output only references the ones it",
    "// needs, so some imports may appear unused at module scope.",
    "void createLeafError; void createBranchError; void createError;",
    "void deepEqual; void typeOf; void wrapErrors;",
    "",
    "const deps = createDeps();",
    "for (const [name, fn] of Object.entries(builtInFormats)) deps.formats.set(name, fn);",
    "",
    "const { validate } = (function (deps) {",
    source,
    "})(deps);",
    "",
    "export { validate };",
    "",
  ].join("\n");
}

/**
 * Formats that the emitted module's `createDeps()` call auto-registers
 * on top of the entries merged in from `builtInFormats`. Mirrors the
 * runtime side of `@oav/schema`'s `createDeps`; if that list ever
 * grows, this set has to grow too.
 */
const SCHEMA_AUTO_REGISTERED_FORMATS: ReadonlySet<string> = new Set(["regex"]);

/**
 * Walk the schema looking for `format: "..."` values referenced on
 * object subschemas; return those not covered by the built-in set or
 * the schema-auto-registered set. Using {@link walkSubschemas} keeps
 * us out of `enum` / `const` / `default` literal values, which might
 * incidentally contain a string under a `format` key without being a
 * format assertion.
 */
function collectUnknownFormats(schema: SchemaOrBoolean): string[] {
  const found = new Set<string>();
  walkSubschemas(schema, (node) => {
    if (typeof node !== "object" || node === null || Array.isArray(node)) return;
    const format = (node as SchemaObject).format;
    if (
      typeof format === "string" &&
      !(format in builtInFormats) &&
      !SCHEMA_AUTO_REGISTERED_FORMATS.has(format)
    ) {
      found.add(format);
    }
  });
  return [...found].sort();
}
